#ifndef _ISDBT_COMMON_H_
#define _ISDBT_COMMON_H_

//#define GPIO_MB86A35S_SPIC_XIRQ 		27	// rev.B
#define GPIO_ISDBT_IRQ 					77	// GPIO_77 FULLSEG_INT_N ????????
//#define GPIO_MB86A35S_FRAME_LOCK		46	// rev.B - not need

//#define GPIO_MB86A35S_SPIS_XIRQ 		16	//rev.B - not need??? rev.C : 62 -> Rev.D :141
#define GPIO_ISDBT_STAND_BY				69
#define GPIO_ISDBT_PWR_EN 				76//GPIO_76 FULLSEG_LDO_EN 	//1.2V, 1.8V (but 2.8V->PMIC)
#define GPIO_ISDBT_RST 					75//GPIO_75 FULLSEG_RESET_N 
//#define GPIO_ISDBT_ANT_SELECT 			169	//rev.B

#define ISDBT_DEFAULT_NOTUSE_MODE -1
#define ISDBT_UHF_MODE 0
#define ISDBT_VHF_MODE 1


#endif //_ISDBT_COMMON_H_
/*
GPIO_89 FULLSEG_TSIF_CLK 
GPIO_90 FULLSEG_TSIF_EN 
GPIO_91 FULLSEG_TSIF_DATA 
GPIO_92 FULLSEG_TSIF_SYNC 

GPIO_47 FULLSEG_I2C_SDA 
GPIO_48 FULLSEG_I2C_SCL 

GPIO_69 FULLSEG_XSTANDBY 
GPIO_75 FULLSEG_RESET_N 
GPIO_76 FULLSEG_LDO_EN 
GPIO_77 FULLSEG_INT_N 

*/