#
# Makefile for the broadcast(TDMB) RF/BB core.
#

obj-$(CONFIG_LGE_BROADCAST_TDMB)		+= broadcast_tdmb_drv_if.o
obj-$(CONFIG_LGE_BROADCAST_TDMB_FC8050)		+= fc8050/
obj-$(CONFIG_LGE_BROADCAST_TDMB_FC8050_Z)		+= fc8050_z/
obj-$(CONFIG_LGE_BROADCAST_TDMB_T3A00)		+= t3a00/
#obj-$		+= t39fx/
#obj-y		+= broadcast_tdmb_drv_if.o
#obj-y		+= lg2102/
#obj-y		+= t3900/
