#
# Makefile for the TDMB T3A00 drivers.
#

# Each configuration option enables a list of files.
# LGE
obj-$(CONFIG_LGE_BROADCAST_TDMB)		+= broadcast_t3a00_drv_if.o
obj-$(CONFIG_LGE_BROADCAST_TDMB)		+= broadcast_t3a00.o
obj-$(CONFIG_LGE_BROADCAST_TDMB)		+= tdmb_tunerbbdrv_t3a00.o
obj-$(CONFIG_LGE_BROADCAST_TDMB)		+= INC_INTERFACE.o
obj-$(CONFIG_LGE_BROADCAST_TDMB)		+= INC_PROCESS.o
obj-$(CONFIG_LGE_BROADCAST_TDMB)		+= INC_FICDEC.o
obj-$(CONFIG_LGE_BROADCAST_TDMB)		+= INC_QFIFO.o
obj-$(CONFIG_LGE_BROADCAST_TDMB)		+= INC_RF_CTRL500.o

#obj-y		+= broadcast_t3a00_drv_if.o
#obj-y		+= broadcast_t3a00.o
#obj-y		+= tdmb_tunerbbdrv_t3a00.o
#obj-y		+= INC_INTERFACE.o
#obj-y		+= INC_PROCESS.o
#obj-y		+= INC_FICDEC.o
#obj-y		+= INC_QFIFO.o
#obj-y		+= INC_RF_CTRL500.o