#
# Makefile for the broadcast(ISDB-T) RF/BB core.
#
#obj-$(CONFIG_LGE_BROADCAST_ONESEG)		+= broadcast_dmb_drv_if.o
obj-$(CONFIG_LGE_BROADCAST_ONESEG_TCC3535)		+= broadcast_dmb_drv_if.o
obj-$(CONFIG_LGE_BROADCAST_ONESEG_MB86A35S)		+= radio-mb86a35/
obj-$(CONFIG_LGE_BROADCAST_ONESEG_FC8150)		+= fc8150/
obj-$(CONFIG_LGE_BROADCAST_ONESEG_TCC3535)		+= tcc3535/
obj-$(CONFIG_LGE_BROADCAST_ONESEG_MB86A36K)		+= radio-mb86a36k/
