obj-y += tcc353x_lna_control.o

EXTRA_CFLAGS += -Idrivers/broadcast/oneseg/tcc3535
EXTRA_CFLAGS += -Idrivers/broadcast/oneseg/tcc3535/Tcc353xDriver/common
EXTRA_CFLAGS += -Idrivers/broadcast/oneseg/tcc3535/Tcc353xDriver/api/inc
EXTRA_CFLAGS += -Idrivers/broadcast/oneseg/tcc3535/Tcc353xDriver/PAL
EXTRA_CFLAGS += -Idrivers/broadcast/oneseg/tcc3535/Tcc353xDriver/sample/monitoring
EXTRA_CFLAGS += -Idrivers/broadcast/oneseg/tcc3535/Tcc353xDriver/sample/main

