#
# Makefile for the sensor drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_SENSOR_LSM330)	+= lsm330_acc.o lsm330_gyr.o
obj-$(CONFIG_SENSOR_APDS9950)	+= apds9950.o
obj-$(CONFIG_SENSOR_AK8963)	+= akm8963.o
obj-$(CONFIG_SENSOR_SHT21)	+= sht21.o
obj-$(CONFIG_SENSOR_BMP18X)	+= bmp18x-i2c.o bmp18x-core.o
